changelog:
  categories:
    - title: ✨ Features
      labels:
        - ✨ feature
    - title: ⚙️ Changes
      labels:
        - ⚙️ change
    - title: 🐛 Bugs
      labels:
        - 🐛 bug
    - title: 🎛️ Tuning
      labels:
        - 🎛️ tuning
    - title: 📘 Documentation
      labels:
        - 📘 doc
